baseurl = "/"
languageCode = "en-us"
title = "Khiem Nguyen"
theme = "hugo-sustain"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/rstudio/blogdown"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/rstudio"

[params]
  avatar = "..\\public\\images\\khienguyen.png"
  author = "Khiem Nguyen"
  description = "Describe your website"